[program:axum-api-dev]
command=/home/appuser/.cargo/bin/cargo-watch -x run
directory=/var/www
#user=appuser
autostart=true
autorestart=true
#stdout_logfile=/var/log/supervisor/axum.log
#stderr_logfile=/var/log/supervisor/axum.err