[program:zig-api-dev]
command=bash -c "zig build run --watch"
directory=/var/www
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/zig_api.log
stderr_logfile=/var/log/supervisor/zig_api.err